package ProjectAuler;

/**
 * Created by max on 1/27/2017.
 */
public class p12 {
    /*
  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
     */
    public static long questionNaive(int divisors) {
       int i = 1;
       long n = 0;
        while (true){
          n += i;
          i++;
          if(numOfDivisors(n)>= divisors) return n;
       }
    }

    private static int numOfDivisors(long n) {
        int d = 2;
        for (long i = 2; i < Math.sqrt(n); i++) {
            if(n%i==0) d+=2;
        }
        return d;
    }


    public static void main(String[] st) {
        p12 q = new p12();

        System.out.println(questionNaive(500));
    }
}
